name: 'nix-statix-action'
description: 'Lint and fix Nix code with Statix, then commit and push the changes or open a pull request'

inputs:
  flags:
    description: 'Command-line flags to statix (e.g. fix, check)'
    required: false
    default: 'fix'
  author:
    description: 'Author name and email in the format `Name <email@address.com>`'
    required: false
    default: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
  committer:
    description: 'Committer name and email'
    required: false
    default: 'GitHub <noreply@github.com>'
  directory:
    description: 'Directory to scan for linting'
    required: false
    default: '.'
  commit_message:
    description: 'Commit message'
    required: false
    default: 'Chore: Lint Nix code with Statix'
  open_pr:
    description: 'Whether to create a pull request instead of pushing directly'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run Statix
      shell: bash
      id: statix
      run: |
        nix run nixpkgs#statix -- ${{ inputs.flags }} ${{ inputs.directory }}

    - name: Commit and push changes or open PR
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git config --global user.name "${{ inputs.author }}"
        git config --global user.email "${{ inputs.author }}"

        git add .
        git diff --staged --quiet && echo "No changes to commit" && exit 0

        git commit -m "${{ inputs.commit_message }}"

        if [ "${{ inputs.open_pr }}" = "true" ]; then
          BRANCH="statix-fix-$(date +%s)"
          git checkout -b "$BRANCH"
          git push origin "$BRANCH"

          gh pr create \
            --title "${{ inputs.commit_message }}" \
            --body "This PR was automatically generated by nix-statix-action to fix Nix code using Statix." \
            --head "$BRANCH" \
            --base "${{ github.ref_name }}"
        else
          git push origin HEAD:${{ github.ref_name }}

branding:
  icon: 'check-circle'
  color: 'green'
