name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Statix Action ${{ github.ref_name }}"
          body: "🚀 Automatically released Statix GitHub Action!"
          draft: false
          prerelease: false
